//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Проект.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductFromPeople
    {
        public string UserName { get; set; }
        public string ProductName { get; set; }
        public double Price { get; set; }
        public int Id { get; set; }
    
        public virtual tableUser tableUser { get; set; }
        public virtual ProductFromStore ProductFromStore { get; set; }

      
    }
}
